### ISSUE TITLE
Product catalog: Page content not styled similarly as the product parent page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#19]
![image](https://cloud.githubusercontent.com/assets/11186313/14058241/3b533318-f355-11e5-9d07-dc60f93a62c8.png)

**Comment by jsemblantetitanweb** [comment]
It is already styled. The design is base on how user inputs the content.

**Comment by roseliesromeo** [comment]
Category description should be styled similarly as the other pages.  It should have the same output for the inputted content as with the other pages.
![image](https://cloud.githubusercontent.com/assets/11186313/14339369/8dfaede0-fcb0-11e5-948b-4518cea832aa.png)

**Comment by roseliesromeo** [comment]
Still able to replicate.  Issue exists for newly created 
![image](https://cloud.githubusercontent.com/assets/11186313/14380805/37472f40-fdb4-11e5-8846-1dd97b055f9c.png)
