### ISSUE TITLE
Designs: Shortened  description shows a distorted ordered list

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#36]
Applicable to Projects gallery page

![image](https://cloud.githubusercontent.com/assets/11186313/14058817/c7796350-f367-11e5-8bb7-cf4ea95536d8.png)

**Comment by jsemblantetitanweb** [comment]
Text is being remove according to this ticket (https://projects.titanweb.com.au/public/index.php?path_info=projects/4000/tasks/34)

**Comment by roseliesromeo** [comment]
Changing the implementation fixed the issue.
