### ISSUE TITLE
Home: Hyperlink is pointed to a local url.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#4]
![image](https://cloud.githubusercontent.com/assets/11186313/14057911/77bb50b2-f349-11e5-892a-0d377300d4b0.png)

**Comment by jsemblantetitanweb** [comment]
This is a user error. The link can be change by the user through inputting it in the content.

**Comment by roseliesromeo** [comment]
This a dev error.
Fixed now.
![image](https://cloud.githubusercontent.com/assets/11186313/14312810/7b98daf8-fc20-11e5-96e7-d3a2e5710b17.png)
