### ISSUE TITLE
Product single: For variable product, the variations are displayed as the additional information instead of as options/selections.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#40]
![image](https://cloud.githubusercontent.com/assets/11186313/14058910/313feeec-f36a-11e5-91b0-a699dd3d299d.png)

**Comment by jsemblantetitanweb** [comment]
This is a user error. The variations are not being done correctly

**Comment by roseliesromeo** [comment]
Variations are added the normal way and works fine now.
