### ISSUE TITLE
Mobile - project gallery: Clipped part of the description text is visible.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#52]
![image](https://cloud.githubusercontent.com/assets/11186313/14079515/00750f9a-f531-11e5-9796-f71efc8a7c51.png)

**Comment by jsemblantetitanweb** [comment]
This part of the page is already being remove according to this ticket.
https://projects.titanweb.com.au/public/index.php?path_info=projects%2F4000%2Ftasks%2F34

**Comment by roseliesromeo** [comment]
Changing the implementation fixed the issue
