### ISSUE TITLE
Product single: It allows two lines for the product title in the related products section but not in the products listing which makes the implementation inconsistent.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#63]
![image](https://cloud.githubusercontent.com/assets/11186313/14090722/96d95c38-f56e-11e5-8eb2-4ebfb2763e81.png)
![image](https://cloud.githubusercontent.com/assets/11186313/14090743/b6052b8c-f56e-11e5-8be3-e72b3386234e.png)

**Comment by jsemblantetitanweb** [comment]
The design is already change in regarding to this ticket (https://projects.titanweb.com.au/public/index.php?path_info=projects/4000/tasks/34). And I already custom it to limit in two lines of title.

**Comment by roseliesromeo** [comment]
All product titles are in one line.
