### ISSUE TITLE
Product single: Inconsistent implementation of the product description field.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#64]
Some products
![image](https://cloud.githubusercontent.com/assets/11186313/14090807/0a87113e-f56f-11e5-98c5-7ddc6533d36b.png)
Others
![image](https://cloud.githubusercontent.com/assets/11186313/14090823/1f07d1ca-f56f-11e5-9f9c-44ed7c027d2b.png)

**Comment by jsemblantetitanweb** [comment]
The first screenshot is a preformatted text. That style is just normal. And for the second screenshot it is already fix
