### ISSUE TITLE
Product single: Add to cart is enabled for products with 0 price.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#65]
![image](https://cloud.githubusercontent.com/assets/11186313/14090879/6d510f5e-f56f-11e5-8e09-210ab59fdec2.png)

**Comment by jsemblantetitanweb** [comment]
Note: If you put a value in the price input in the admin side of the product the price will display even if you input "0" on it. But if you leave it blank the price wont display.
