### ISSUE TITLE
Cart page: It updates the cart but at the same time an error prompts if inputted quantity exceeds the number of available stocks.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#66]
![image](https://cloud.githubusercontent.com/assets/11186313/14090959/e24aa9dc-f56f-11e5-8da5-410e3518ea34.png)

**Comment by jsemblantetitanweb** [comment]
It updates the cart but it can't proceed to checkout since the error occurs. I think this is not a bug.

**Comment by roseliesromeo** [comment]
It is confusing.  It shouldn't display both prompts.
Refer to this:
http://unusualpetvets.stage.titanweb.com.au/cart/
![image](https://cloud.githubusercontent.com/assets/11186313/14308793/048dcea6-fc0b-11e5-9d9b-c02e5ae0a3bf.png)
