### ISSUE TITLE
Cart: Buttons aren't aligned.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#7]
![image](https://cloud.githubusercontent.com/assets/11186313/14057977/75885f5e-f34b-11e5-82bd-55892c756c8d.png)

**Comment by jsemblantetitanweb** [comment]
Note: Coupon button is already been remove due to this ticket (https://projects.titanweb.com.au/public/index.php?path_info=projects%2F4000%2Ftasks%2F34)

**Comment by roseliesromeo** [comment]
Removing the other button fixed the issue.
