### ISSUE TITLE
Checkout: Bullet marks are displayed beside the payment options.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#8]
![image](https://cloud.githubusercontent.com/assets/11186313/14058010/8a950aae-f34c-11e5-8c8e-8974079a44da.png)

**Comment by jsemblantetitanweb** [comment]
Note: This payment section is already been remove due to this ticket request https://projects.titanweb.com.au/public/index.php?path_info=projects%2F4000%2Ftasks%2F34
