### ISSUE TITLE
General: Grey scale version of the logo shouldn't be used as the default no image as per requested by Bill. Just a gray background without the text.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#82]
https://projects.titanweb.com.au/public/index.php?path_info=projects/dva-fabrication-pack4-responsive-rebuild/tasks/36
"Change the background of all product images to the same grey as the default image (without text) as the client is going to provide PNG images for those which do not fit currently). Please note, we want to keep the default image as it is as well"

**Comment by jsemblantetitanweb** [comment]
https://projects.titanweb.com.au/public/index.php?path_info=projects/dva-fabrication-pack4-responsive-rebuild/tasks/36

Bill have some changes regarding this. See ticket link comment # 6. Thanks

**Comment by roseliesromeo** [comment]
I can't find additional instruction regarding the default no image from the link provided above.
