### ISSUE TITLE
Product single: Add to Order should be displayed right below the Qty field.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#88]
![image](https://cloud.githubusercontent.com/assets/11186313/14416380/20ecfe26-ffdc-11e5-8552-fa66c99cf1d1.png)

**Comment by jsemblantetitanweb** [comment]
This is related to this ticket link https://projects.titanweb.com.au/public/index.php?path_info=projects/4000/tasks/34 . Bill request in Comment #11 to make the color choices display above the add to order button.
