### ISSUE TITLE
Catalogues: Clicking the feature image will lead to a PDF file but will not open in new tab.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#90]
![image](https://cloud.githubusercontent.com/assets/11186313/14418181/04fe709c-ffef-11e5-8cae-eafabd754faa.png)

**Comment by jsemblantetitanweb** [comment]
@note: The image is part of the content. The client can set it in the admin side to open in a new tab or not.
