### ISSUE TITLE
Catalogues: Contact us hyperlink doesn't redirect to the contact us page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#91]
![image](https://cloud.githubusercontent.com/assets/11186313/14418214/49eb59fe-ffef-11e5-8ed7-cb1cb165cf47.png)

**Comment by jsemblantetitanweb** [comment]
@note: This can be set in the admin side. This is part of the content. The client can set its hyperlink by editing the content.

**Comment by roseliesromeo** [comment]
Contact us is linked to a local address.
![image](https://cloud.githubusercontent.com/assets/11186313/14481336/8e8d537a-0164-11e6-8e1b-82a6663e7039.png)
