### ISSUE TITLE
Product single: Font is not set to Raleway medium 17px but instead to Lato 16px.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/DVA-Fabrications#95]
![image](https://cloud.githubusercontent.com/assets/11186313/14419217/c538a682-fff6-11e5-9794-aa8b9ec70272.png)

**Comment by jsemblantetitanweb** [comment]
This is related to this ticket https://projects.titanweb.com.au/public/index.php?path_info=projects/4000/tasks/34 Comment #9.
